baseURL = "https://www.liamwhite.blog"
title = "Liam White"
theme = ["hugo-coder", "reveal"]

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

enableGitInfo = true

googleAnalytics = "G-CEPR8VKJP7"
